package com.ygy.model;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Mon Nov 13 11:46:25 CST 2017
     */
    private Integer id;
    private String time;

    public void setTime(String time) {
        this.time = time;
    }

    public String getTime() {
        return time;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log
     *
     * @mbggenerated Mon Nov 13 11:46:25 CST 2017
     */
    private String log;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Mon Nov 13 11:46:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Mon Nov 13 11:46:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log
     *
     * @return the value of log.log
     *
     * @mbggenerated Mon Nov 13 11:46:25 CST 2017
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log
     *
     * @param log the value for log.log
     *
     * @mbggenerated Mon Nov 13 11:46:25 CST 2017
     */
    public void setLog(String log) {
        this.log = log;
    }
}